version: 2

before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - format_overrides:
      - goos: darwin
        format: Darwin
      - goos: linux
        format: Linux
      - goos: windows
        format: Windows
      - goarch: 386
        format: i386
      - goarch: amd64
        format: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

